[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autorestart=true
priority=10

[program:sshd]
command=/usr/sbin/sshd -D -e
autorestart=true
priority=20

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=30

[program:firewall_logger]
command=/usr/bin/python3 /opt/lab-target/firewall_logger.py
autorestart=true
priority=40
